_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "pretrained_models/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 5
DATASETS:
  TRAIN: ("dla_train",)
  TEST: ("dla_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
DATALOADER:
  NUM_WORKERS: 1

